// flow-typed signature: 0a20caaf4d32b08ad25a43a37b0b60dd
// flow-typed version: <<STUB>>/prettier_v^0.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier/bin/prettier' {
  declare module.exports: any;
}

declare module 'prettier/src/comments' {
  declare module.exports: any;
}

declare module 'prettier/src/fast-path' {
  declare module.exports: any;
}

declare module 'prettier/src/options' {
  declare module.exports: any;
}

declare module 'prettier/src/pp' {
  declare module.exports: any;
}

declare module 'prettier/src/printer' {
  declare module.exports: any;
}

declare module 'prettier/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier/bin/prettier.js' {
  declare module.exports: $Exports<'prettier/bin/prettier'>;
}
declare module 'prettier/index' {
  declare module.exports: $Exports<'prettier'>;
}
declare module 'prettier/index.js' {
  declare module.exports: $Exports<'prettier'>;
}
declare module 'prettier/src/comments.js' {
  declare module.exports: $Exports<'prettier/src/comments'>;
}
declare module 'prettier/src/fast-path.js' {
  declare module.exports: $Exports<'prettier/src/fast-path'>;
}
declare module 'prettier/src/options.js' {
  declare module.exports: $Exports<'prettier/src/options'>;
}
declare module 'prettier/src/pp.js' {
  declare module.exports: $Exports<'prettier/src/pp'>;
}
declare module 'prettier/src/printer.js' {
  declare module.exports: $Exports<'prettier/src/printer'>;
}
declare module 'prettier/src/util.js' {
  declare module.exports: $Exports<'prettier/src/util'>;
}
